version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: musicdude45/sveltetest:latest
    ports:
      - "5173:5173"  # Default Vite dev server port
    volumes:
      - .:/app
      - /app/node_modules  # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
